import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';

const Terms: React.FC = () => {
    return (
        <div className="min-h-screen bg-slate-50 py-12 px-4">
            <div className="max-w-3xl mx-auto">
                <Link to="/login" className="inline-flex items-center gap-2 text-edexcel-blue hover:text-edexcel-teal mb-6">
                    <ArrowLeft size={18} />
                    Back to Login
                </Link>

                <div className="bg-white rounded-2xl shadow-lg p-8">
                    <h1 className="text-3xl font-bold text-gray-900 mb-2">Terms of Service</h1>
                    <p className="text-gray-500 mb-8">Last updated: December 2024 | Version 2.0</p>

                    <div className="prose prose-gray max-w-none">
                        <h2 className="text-xl font-bold text-gray-800 mt-6 mb-3">1. Assessment & Educational Disclaimer</h2>
                        <div className="bg-amber-50 border border-amber-200 rounded-lg p-4 mb-4">
                            <p className="text-amber-800 font-medium mb-2">⚠️ Important Notice</p>
                            <p className="text-amber-700 text-sm">
                                GoGCSE is an independent educational practice platform. We are NOT an exam board and NOT affiliated with Pearson Edexcel, AQA, OCR, or Ofqual.
                            </p>
                        </div>
                        <ul className="list-disc pl-6 space-y-2 text-gray-700">
                            <li><strong>NO QUALIFICATIONS:</strong> Use of this site does NOT confer any official grade, qualification,/certification, or academic credit.</li>
                            <li><strong>INDICATIVE SCORING:</strong> "Marks", "Grades", and "Levels" displayed on this platform are estimates generated by AI for practice purposes only. They may not reflect the grade you would achieve in a real examination.</li>
                            <li><strong>NO RELIANCE:</strong> You should not rely on these results for university applications, employment, or any other formal purpose.</li>
                        </ul>

                        <h2 className="text-xl font-bold text-gray-800 mt-8 mb-3">2. AI-Generated Content</h2>
                        <p className="text-gray-700 mb-3">GoGCSE uses artificial intelligence (AI) technology to generate:</p>
                        <ul className="list-disc pl-6 space-y-1 text-gray-700">
                            <li>Practice exam questions and source texts</li>
                            <li>Automated marking and feedback</li>
                            <li>Model answers and suggestions</li>
                        </ul>

                        <h3 className="text-lg font-bold text-gray-800 mt-4 mb-2">2a. Teacher Classroom Features</h3>
                        <p className="text-gray-700 mb-2">
                            If you join a "Classroom" using an invite code:
                        </p>
                        <ul className="list-disc pl-6 space-y-1 text-gray-700">
                            <li>You grant the verified teacher of that class access to view your name and assignment results for that specific class.</li>
                            <li>Assignments generated by teachers are AI-created and subject to the same limitations as other platform content.</li>
                            <li>You can leave a class at any time, which will remove the teacher's access to your future data.</li>
                        </ul>

                        <p className="text-gray-700 mt-3">
                            <strong>AI Limitations:</strong> AI-generated content may contain errors, inaccuracies, or hallucinations.
                            It cannot replace the professional judgement of qualified teachers. Always verify key information with official sources.
                        </p>

                        <h2 className="text-xl font-bold text-gray-800 mt-8 mb-3">3. User Eligibility & Conduct</h2>
                        <ul className="list-disc pl-6 space-y-2 text-gray-700">
                            <li><strong>Age Requirement:</strong> You must be at least 13 years old to create an account. If you are under 13, you may not use this service.</li>
                            <li><strong>Teacher Accounts:</strong> Teachers warrant that they have appropriate authority to invite students to the platform.</li>
                            <li><strong>Prohibited Conduct:</strong> You agree not to upload personal data (names, addresses) in free-text fields or submission boxes. You agree not to use the platform for bullying, harassment, or generating harmful content.</li>
                        </ul>

                        <h2 className="text-xl font-bold text-gray-800 mt-8 mb-3">4. Limitation of Liability</h2>
                        <p className="text-gray-700">
                            To the maximum extent permitted by law (and without excluding liability for death or personal injury caused by negligence):
                        </p>
                        <ul className="list-disc pl-6 space-y-2 text-gray-700 mt-2">
                            <li>We are not liable for any loss of academic performance, exam failure, or missed opportunities.</li>
                            <li>We are not liable for any indirect or consequential losses.</li>
                            <li>Our total liability to you in contract, tort, or otherwise is limited to the amount you paid us (if any) in the 12 months preceding the claim.</li>
                        </ul>

                        <h2 className="text-xl font-bold text-gray-800 mt-8 mb-3">5. Intellectual Property</h2>
                        <p className="text-gray-700">
                            All content on GoGCSE, including generated questions and model answers, is protected by copyright.
                            "GCSE" is a registered trademark of the examination boards. We use these terms purely for descriptive purposes to indicate compatibility with the curriculum.
                        </p>

                        <h2 className="text-xl font-bold text-gray-800 mt-8 mb-3">6. Governing Law</h2>
                        <p className="text-gray-700">
                            These terms are governed by the laws of England and Wales. Any disputes will be subject to the exclusive jurisdiction of the courts of England and Wales.
                        </p>

                        <h2 className="text-xl font-bold text-gray-800 mt-8 mb-3">7. Contact</h2>
                        <p className="text-gray-700">
                            For support or legal inquiries, please contact us via the help link on the dashboard.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default Terms;
